// src/components/layout/AppHeader.vue
<template>
  <header class="fixed top-0 left-0 right-0 z-50 bg-slate-900/80 backdrop-blur-md border-b border-white/10">
    <nav class="flex justify-between items-center max-w-7xl mx-auto px-6 py-4">
      <!-- Logo CodeCraft -->
      <router-link to="/" class="flex items-center group">
        <img
          src="/logo-code2.png"
          alt="CodeCraft Studio"
          style="height: 48px; width: auto; display: block;"
          class="group-hover:scale-105 transition-transform duration-300"
        />
      </router-link>

      <!-- Navigation Desktop -->
      <div class="hidden md:flex space-x-8">
        <router-link
          to="/"
          :class="[
            'text-gray-300 hover:text-primary-400 transition-all duration-300 cursor-pointer relative group font-medium',
            $route.path === '/' ? 'text-primary-400' : ''
          ]"
        >
          Home
          <span class="absolute -bottom-1 left-0 w-0 h-0.5 bg-primary-400 transition-all duration-300 group-hover:w-full"></span>
        </router-link>
        <router-link
          to="/servizi"
          :class="[
            'text-gray-300 hover:text-primary-400 transition-all duration-300 cursor-pointer relative group font-medium',
            $route.path === '/servizi' ? 'text-primary-400' : ''
          ]"
        >
          Servizi
          <span class="absolute -bottom-1 left-0 w-0 h-0.5 bg-primary-400 transition-all duration-300 group-hover:w-full"></span>
        </router-link>
        <router-link
          to="/tool"
          :class="[
            'text-gray-300 hover:text-primary-400 transition-all duration-300 cursor-pointer relative group font-medium',
            $route.path === '/tool' ? 'text-primary-400' : ''
          ]"
        >
          Progetti
          <span class="absolute -bottom-1 left-0 w-0 h-0.5 bg-primary-400 transition-all duration-300 group-hover:w-full"></span>
        </router-link>
        <router-link
          to="/contatti"
          :class="[
            'text-gray-300 hover:text-primary-400 transition-all duration-300 cursor-pointer relative group font-medium',
            $route.path === '/contatti' ? 'text-primary-400' : ''
          ]"
        >
          Contatti
          <span class="absolute -bottom-1 left-0 w-0 h-0.5 bg-primary-400 transition-all duration-300 group-hover:w-full"></span>
        </router-link>
      </div>

      <!-- CTA Button Desktop -->
      <div class="hidden md:block">
        <BaseButton
          tag="router-link"
          to="/contatti"
          variant="primary"
          size="md"
        >
          <span>Contattaci</span>
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
          </svg>
        </BaseButton>
      </div>

      <!-- Mobile Menu Button -->
      <button
        @click="toggleMobileMenu"
        class="md:hidden text-white hover:text-primary-400 transition-colors p-2 rounded-lg hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-primary-400/50"
        :class="{ 'text-primary-400': isMobileMenuOpen }"
      >
        <svg class="w-6 h-6 transition-transform duration-300" :class="{ 'rotate-90': isMobileMenuOpen }" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path
            v-if="!isMobileMenuOpen"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4 6h16M4 12h16M4 18h16"
          />
          <path
            v-else
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      </button>
    </nav>

    <!-- Mobile Menu -->
    <Transition name="slide-down">
      <div
        v-if="isMobileMenuOpen"
        class="md:hidden absolute top-full left-0 right-0 bg-slate-900/95 backdrop-blur-sm border-t border-white/10 mx-6 rounded-b-2xl shadow-2xl"
      >
        <div class="flex flex-col space-y-2 p-6">
          <router-link
            to="/"
            @click="closeMobileMenu"
            :class="[
              'text-gray-300 hover:text-primary-400 transition-colors py-3 px-4 rounded-lg hover:bg-white/10 flex items-center space-x-3',
              $route.path === '/' ? 'text-primary-400 bg-primary-400/10' : ''
            ]"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/>
            </svg>
            <span>Home</span>
          </router-link>
          <router-link
            to="/servizi"
            @click="closeMobileMenu"
            :class="[
              'text-gray-300 hover:text-primary-400 transition-colors py-3 px-4 rounded-lg hover:bg-white/10 flex items-center space-x-3',
              $route.path === '/servizi' ? 'text-primary-400 bg-primary-400/10' : ''
            ]"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"/>
            </svg>
            <span>Servizi</span>
          </router-link>
          <router-link
            to="/tool"
            @click="closeMobileMenu"
            :class="[
              'text-gray-300 hover:text-primary-400 transition-colors py-3 px-4 rounded-lg hover:bg-white/10 flex items-center space-x-3',
              $route.path === '/tool' ? 'text-primary-400 bg-primary-400/10' : ''
            ]"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
            </svg>
            <span>Progetti</span>
          </router-link>
          <router-link
            to="/contatti"
            @click="closeMobileMenu"
            :class="[
              'text-gray-300 hover:text-primary-400 transition-colors py-3 px-4 rounded-lg hover:bg-white/10 flex items-center space-x-3',
              $route.path === '/contatti' ? 'text-primary-400 bg-primary-400/10' : ''
            ]"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/>
            </svg>
            <span>Contatti</span>
          </router-link>

          <!-- Mobile CTA Button -->
          <div class="pt-4 border-t border-white/10 mt-4">
            <BaseButton
              tag="router-link"
              to="/contatti"
              variant="primary"
              size="md"
              full-width
              @click="closeMobileMenu"
            >
              <span>Contattaci</span>
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
              </svg>
            </BaseButton>
          </div>
        </div>
      </div>
    </Transition>
  </header>
</template>

<script setup>
import { ref } from 'vue'
import BaseButton from '@/components/common/BaseButton.vue'

const isMobileMenuOpen = ref(false)

const toggleMobileMenu = () => {
  isMobileMenuOpen.value = !isMobileMenuOpen.value
}

const closeMobileMenu = () => {
  isMobileMenuOpen.value = false
}
</script>

<style scoped>
/* Mobile menu transitions */
.slide-down-enter-active,
.slide-down-leave-active {
  transition: all 0.3s ease;
}

.slide-down-enter-from {
  opacity: 0;
  transform: translateY(-10px);
}

.slide-down-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}

/* Active section indicator line */
.group:hover span {
  width: 100%;
}

/* Focus styles for accessibility */
button:focus-visible {
  outline: 2px solid theme('colors.primary.400');
  outline-offset: 2px;
}

a:focus-visible {
  outline: 2px solid theme('colors.primary.400');
  outline-offset: 2px;
  border-radius: 4px;
}
</style>

// components/layout/AppHeader.jsx
'use client'

import Link from 'next/link'
import Image from 'next/image'
import { usePathname } from 'next/navigation'
import { useState } from 'react'
import BaseButton from '@/components/common/BaseButton'
import { ArrowRight, Home, Briefcase, Zap, Mail } from 'lucide-react'

export default function AppHeader() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const pathname = usePathname()

  const navigation = [
    { name: 'Home', href: '/', icon: Home },
    { name: 'Servizi', href: '/servizi', icon: Briefcase },
    { name: 'Progetti', href: '/tool', icon: Zap },
    { name: 'Contatti', href: '/contatti', icon: Mail },
  ]

  const closeMobileMenu = () => {
    setMobileMenuOpen(false)
  }

  return (
    <header className="fixed top-0 left-0 right-0 z-50 bg-slate-900/80 backdrop-blur-md border-b border-white/10">
      <nav className="flex justify-between items-center max-w-7xl mx-auto px-6 py-4">
        {/* Logo CodeCraft */}
        <Link href="/" className="flex items-center group">
          <Image
            src="/logo-code2.png"
            alt="CodeCraft Studio"
            width={192}
            height={48}
            priority
            className="h-12 w-auto group-hover:scale-105 transition-transform duration-300"
          />
        </Link>

        {/* Navigation Desktop */}
        <div className="hidden md:flex space-x-8">
          {navigation.map((item) => (
            <Link
              key={item.name}
              href={item.href}
              className={`
                text-gray-300 hover:text-rose-400 transition-all duration-300 cursor-pointer relative group font-medium
                ${pathname === item.href ? 'text-rose-400' : ''}
              `}
            >
              {item.name}
              <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-rose-400 transition-all duration-300 group-hover:w-full"></span>
            </Link>
          ))}
        </div>

        {/* CTA Button Desktop */}
        <div className="hidden md:block">
          <BaseButton
            to="/contatti"
            variant="primary"
            size="md"
            rightIcon={ArrowRight}
          >
            Contattaci
          </BaseButton>
        </div>

        {/* Mobile Menu Button */}
        <button
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          className={`
            md:hidden text-white hover:text-rose-400 transition-colors p-2 rounded-lg
            hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-rose-400/50
            ${mobileMenuOpen ? 'text-rose-400' : ''}
          `}
        >
          <svg
            className={`w-6 h-6 transition-transform duration-300 ${mobileMenuOpen ? 'rotate-90' : ''}`}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            {!mobileMenuOpen ? (
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4 6h16M4 12h16M4 18h16"
              />
            ) : (
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M6 18L18 6M6 6l12 12"
              />
            )}
          </svg>
        </button>
      </nav>

      {/* Mobile Menu */}
      <div
        className={`
          md:hidden absolute top-full left-0 right-0 bg-slate-900/95 backdrop-blur-sm
          border-t border-white/10 mx-6 rounded-b-2xl shadow-2xl
          transition-all duration-300 ease-in-out origin-top
          ${mobileMenuOpen
            ? 'opacity-100 translate-y-0 scale-y-100'
            : 'opacity-0 -translate-y-2 scale-y-95 pointer-events-none'
          }
        `}
      >
        <div className="flex flex-col space-y-2 p-6">
          {navigation.map((item) => {
            const Icon = item.icon
            return (
              <Link
                key={item.name}
                href={item.href}
                onClick={closeMobileMenu}
                className={`
                  text-gray-300 hover:text-rose-400 transition-colors py-3 px-4
                  rounded-lg hover:bg-white/10 flex items-center space-x-3
                  ${pathname === item.href ? 'text-rose-400 bg-rose-400/10' : ''}
                `}
              >
                <Icon className="w-5 h-5" />
                <span>{item.name}</span>
              </Link>
            )
          })}

          {/* Mobile CTA Button */}
          <div className="pt-4 border-t border-white/10 mt-4">
            <BaseButton
              to="/contatti"
              variant="primary"
              size="md"
              className="w-full"
              rightIcon={ArrowRight}
              onClick={closeMobileMenu}
            >
              Contattaci
            </BaseButton>
          </div>
        </div>
      </div>
    </header>
  )
}
